/// <reference path="../../../include.d.ts" />

var os = require('os');
var supertest = require('supertest');
var should = require("should");
var conf = require('../../../configuration.js');
var CONST = conf.CONST;
var util = require('../../../toolkits.js');
var __path = util.getPath;

var tester = supertest.agent('http://app.milanoo.com');

describe('楼层', function () {
    it('获取首页楼层', function (done) {
        var expected = {
            "msg": "操作成功",
            "code": "0",
            "list": [{
                "is_active": 1,
                "is_displaySonCate": 1,
                "top_key": "women",
                "cmsType": 6,
                "cmsTypeId": "",
                "display_style": 2,
                "pid": -1,
                "display_name": "Women",
                "is_display_red": 0,
                "is_wordOrPic": 1,
                "url": "/women-home/",
                "category_level": 0,
                "is_endColumn": 0,
                "children": [{
                    "is_active": 1,
                    "is_displaySonCate": 1,
                    "cmsType": 1,
                    "cmsTypeId": "1324",
                    "display_style": 0,
                    "pid": 25118,
                    "display_name": "Dresses",
                    "is_display_red": 1,
                    "is_wordOrPic": 1,
                    "url": "/Buy-Women-S-Dresses-c1324",
                    "category_level": 1,
                    "is_endColumn": 0,
                    "category_icon": "",
                    "seo_name": "Women's Dresses",
                    "is_displayCms": 1,
                    "id": 26720,
                    "pic_url": "homecms/2016/201606/20160627/_cms_1466999100.jpg",
                    "left_or_right": 1
                },
                    {
                        "is_active": 1,
                        "is_displaySonCate": 1,
                        "cmsType": 1,
                        "cmsTypeId": "921",
                        "display_style": 0,
                        "pid": 25118,
                        "display_name": "Clubwear",
                        "is_display_red": 1,
                        "is_wordOrPic": 1,
                        "url": "/Buy-Clubwear-c921",
                        "category_level": 1,
                        "is_endColumn": 0,
                        "category_icon": "",
                        "seo_name": "Clubwear",
                        "is_displayCms": 1,
                        "id": 938747,
                        "pic_url": "homecms/2016/201606/20160627/_cms_1466999166.jpg",
                        "left_or_right": 1
                    },
                    {
                        "is_active": 1,
                        "is_displaySonCate": 1,
                        "cmsType": 1,
                        "cmsTypeId": "1140",
                        "display_style": 0,
                        "pid": 25118,
                        "display_name": "Lingerie",
                        "is_display_red": 1,
                        "is_wordOrPic": 1,
                        "url": "/Buy-Lingerie-c1140",
                        "category_level": 1,
                        "is_endColumn": 0,
                        "category_icon": "",
                        "seo_name": "Lingerie",
                        "is_displayCms": 1,
                        "id": 934001,
                        "pic_url": "homecms/2016/201604/20160427/_cms_1461734763.jpg",
                        "left_or_right": 1
                    },
                    {
                        "is_active": 1,
                        "is_displaySonCate": 1,
                        "cmsType": 1,
                        "cmsTypeId": "603",
                        "display_style": 0,
                        "pid": 25118,
                        "display_name": "Swimsuits & Cover-Ups",
                        "is_display_red": 1,
                        "is_wordOrPic": 1,
                        "url": "/Buy-Swimsuits-c603",
                        "category_level": 1,
                        "is_endColumn": 1,
                        "category_icon": "",
                        "seo_name": "Swimsuits",
                        "is_displayCms": 1,
                        "id": 938735,
                        "pic_url": "homecms/2016/201606/20160627/_cms_1466999196.jpg",
                        "left_or_right": 1
                    },
                    {
                        "is_active": 1,
                        "is_displaySonCate": 1,
                        "cmsType": 1,
                        "cmsTypeId": "1333",
                        "display_style": 0,
                        "pid": 25118,
                        "display_name": "Jumpsuits & Rompers",
                        "is_display_red": 0,
                        "is_wordOrPic": 1,
                        "url": "/Buy-Jumpsuits-Rompers-c1333",
                        "category_level": 1,
                        "is_endColumn": 0,
                        "category_icon": "",
                        "seo_name": "Jumpsuits & Rompers",
                        "is_displayCms": 1,
                        "id": 938751,
                        "pic_url": "homecms/2016/201606/20160627/_cms_1466999177.jpg",
                        "left_or_right": 1
                    },
                    {
                        "is_active": 1,
                        "is_displaySonCate": 1,
                        "cmsType": 1,
                        "cmsTypeId": "542",
                        "display_style": 0,
                        "pid": 25118,
                        "display_name": "Tops",
                        "is_display_red": 0,
                        "is_wordOrPic": 1,
                        "url": "/Buy-Tops-c542",
                        "category_level": 1,
                        "is_endColumn": 0,
                        "category_icon": "",
                        "seo_name": "Tops",
                        "is_displayCms": 1,
                        "id": 938761,
                        "pic_url": "homecms/2016/201606/20160627/_cms_1466999312.jpg",
                        "left_or_right": 1
                    },
                    {
                        "is_active": 1,
                        "is_displaySonCate": 1,
                        "cmsType": 1,
                        "cmsTypeId": "540",
                        "display_style": 2,
                        "pid": 938773,
                        "display_name": "Skirts",
                        "is_display_red": 0,
                        "is_wordOrPic": 1,
                        "url": "/Buy-Skirts-c540",
                        "category_level": 2,
                        "is_endColumn": 0,
                        "category_icon": "",
                        "seo_name": "Skirts",
                        "is_displayCms": 0,
                        "id": 938775,
                        "pic_url": "homecms/2016/201606/20160627/_cms_1466991986.jpg",
                        "left_or_right": 1
                    },
                    {
                        "is_active": 1,
                        "is_displaySonCate": 1,
                        "cmsType": 1,
                        "cmsTypeId": "538",
                        "display_style": 0,
                        "pid": 25118,
                        "display_name": "Outerwear",
                        "is_display_red": 1,
                        "is_wordOrPic": 1,
                        "url": "/Buy-Outerwear-c538",
                        "category_level": 1,
                        "is_endColumn": 0,
                        "category_icon": "",
                        "seo_name": "Outerwear",
                        "is_displayCms": 1,
                        "id": 938793,
                        "pic_url": "homecms/2016/201606/20160627/_cms_1466999300.jpg",
                        "left_or_right": 1
                    },
                    {
                        "is_active": 1,
                        "is_displaySonCate": 1,
                        "cmsType": 1,
                        "cmsTypeId": "8772",
                        "display_style": 2,
                        "pid": 937197,
                        "display_name": "Wigs",
                        "is_display_red": 0,
                        "is_wordOrPic": 1,
                        "url": "/Buy-Women-S-Wigs-c8772",
                        "category_level": 2,
                        "is_endColumn": 0,
                        "category_icon": "hot",
                        "seo_name": "Fashion Wigs",
                        "is_displayCms": 1,
                        "id": 937205,
                        "pic_url": "homecms/2016/201604/20160427/_cms_1461734799.jpg",
                        "left_or_right": 1
                    },
                    {
                        "is_active": 1,
                        "is_displaySonCate": 1,
                        "cmsType": 1,
                        "cmsTypeId": "1282",
                        "display_style": 2,
                        "pid": 937197,
                        "display_name": "Makeup",
                        "is_display_red": 0,
                        "is_wordOrPic": 1,
                        "url": "/Buy-Makeup-c1282",
                        "category_level": 2,
                        "is_endColumn": 0,
                        "category_icon": "",
                        "seo_name": "Makeup",
                        "is_displayCms": 1,
                        "id": 937199,
                        "pic_url": "homecms/2015/201510/20151027/_cms_1445939552.jpg",
                        "left_or_right": 1
                    }],
                "seo_name": "women",
                "is_displayCms": 1,
                "id": 25118,
                "position": 1738,
                "left_or_right": 1
            },
                {
                    "is_active": 1,
                    "is_displaySonCate": 1,
                    "top_key": "men",
                    "cmsType": 6,
                    "cmsTypeId": "",
                    "display_style": 2,
                    "pid": -1,
                    "display_name": "Men",
                    "is_display_red": 0,
                    "is_wordOrPic": 1,
                    "url": "/men-home/",
                    "category_level": 0,
                    "is_endColumn": 0,
                    "children": [{
                        "is_active": 1,
                        "is_displaySonCate": 1,
                        "cmsType": 1,
                        "cmsTypeId": "1122",
                        "display_style": 2,
                        "pid": 25278,
                        "display_name": "Ties",
                        "is_display_red": 0,
                        "is_wordOrPic": 1,
                        "url": "/Buy-Men-S-Ties-c1122",
                        "category_level": 2,
                        "is_endColumn": 0,
                        "category_icon": "",
                        "seo_name": "Men's Ties",
                        "is_displayCms": 1,
                        "id": 933126,
                        "pic_url": "",
                        "left_or_right": 1
                    },
                        {
                            "is_active": 0,
                            "is_displaySonCate": 1,
                            "cmsType": 1,
                            "cmsTypeId": "2422",
                            "display_style": 2,
                            "pid": 25278,
                            "display_name": "Cufflinks",
                            "is_display_red": 0,
                            "is_wordOrPic": 1,
                            "url": "/Buy-Cufflinks-c2422",
                            "category_level": 2,
                            "is_endColumn": 0,
                            "category_icon": "",
                            "seo_name": "Cufflinks",
                            "is_displayCms": 1,
                            "id": 933128,
                            "pic_url": "",
                            "left_or_right": 1
                        },
                        {
                            "is_active": 1,
                            "is_displaySonCate": 1,
                            "cmsType": 1,
                            "cmsTypeId": "1175",
                            "display_style": 2,
                            "pid": 25278,
                            "display_name": "Caps/Hats",
                            "is_display_red": 0,
                            "is_wordOrPic": 1,
                            "url": "/Buy-Men-S-Caps-Hats-c1175",
                            "category_level": 2,
                            "is_endColumn": 0,
                            "category_icon": "",
                            "seo_name": "Men's Caps/Hats",
                            "is_displayCms": 1,
                            "id": 933132,
                            "pic_url": "",
                            "left_or_right": 1
                        },
                        {
                            "is_active": 1,
                            "is_displaySonCate": 1,
                            "cmsType": 1,
                            "cmsTypeId": "8766",
                            "display_style": 2,
                            "pid": 25278,
                            "display_name": "Glasses",
                            "is_display_red": 0,
                            "is_wordOrPic": 1,
                            "url": "/Buy-Men-S-Glasses-c8766",
                            "category_level": 2,
                            "is_endColumn": 0,
                            "category_icon": "",
                            "seo_name": "Men's Glasses",
                            "is_displayCms": 1,
                            "id": 933901,
                            "pic_url": "",
                            "left_or_right": 1
                        },
                        {
                            "is_active": 1,
                            "is_displaySonCate": 1,
                            "cmsType": 1,
                            "cmsTypeId": "1178",
                            "display_style": 2,
                            "pid": 25278,
                            "display_name": "Scarves & Wraps",
                            "is_display_red": 0,
                            "is_wordOrPic": 1,
                            "url": "/Buy-Men-S-Scarves-Wraps-c1178",
                            "category_level": 2,
                            "is_endColumn": 0,
                            "category_icon": "",
                            "seo_name": "Men's Scarves & Wraps",
                            "is_displayCms": 1,
                            "id": 933134,
                            "pic_url": "",
                            "left_or_right": 1
                        },
                        {
                            "is_active": 1,
                            "is_displaySonCate": 1,
                            "cmsType": 1,
                            "cmsTypeId": "1501",
                            "display_style": 2,
                            "pid": 25278,
                            "display_name": "Men Gloves",
                            "is_display_red": 0,
                            "is_wordOrPic": 1,
                            "url": "/Buy-Men-Gloves-c1501",
                            "category_level": 2,
                            "is_endColumn": 0,
                            "category_icon": "new",
                            "seo_name": "Men Gloves",
                            "is_displayCms": 1,
                            "id": 933136,
                            "pic_url": "",
                            "left_or_right": 1
                        },
                        {
                            "is_active": 1,
                            "is_displaySonCate": 1,
                            "cmsType": 1,
                            "cmsTypeId": "1162",
                            "display_style": 2,
                            "pid": 933780,
                            "display_name": "Jackets",
                            "is_display_red": 0,
                            "is_wordOrPic": 1,
                            "url": "/Buy-Men-S-Jackets-c1162",
                            "category_level": 3,
                            "is_endColumn": 0,
                            "category_icon": "",
                            "seo_name": "Men's Jackets",
                            "is_displayCms": 1,
                            "id": 933782,
                            "pic_url": "homecms/2016/201604/20160427/_cms_1461735513.jpg",
                            "left_or_right": 1
                        },
                        {
                            "is_active": 1,
                            "is_displaySonCate": 1,
                            "cmsType": 1,
                            "cmsTypeId": "1165",
                            "display_style": 2,
                            "pid": 933780,
                            "display_name": "Coats",
                            "is_display_red": 0,
                            "is_wordOrPic": 1,
                            "url": "/Buy-Men-S-Coats-c1165",
                            "category_level": 3,
                            "is_endColumn": 0,
                            "category_icon": "",
                            "seo_name": "Men's Coats",
                            "is_displayCms": 1,
                            "id": 933784,
                            "pic_url": "homecms/2016/201604/20160427/_cms_1461735503.jpg",
                            "left_or_right": 1
                        },
                        {
                            "is_active": 1,
                            "is_displaySonCate": 1,
                            "cmsType": 1,
                            "cmsTypeId": "8770",
                            "display_style": 2,
                            "pid": 25278,
                            "display_name": "Men's Wigs",
                            "is_display_red": 0,
                            "is_wordOrPic": 1,
                            "url": "/Buy-Men-S-Wigs-c8770",
                            "category_level": 2,
                            "is_endColumn": 0,
                            "category_icon": "",
                            "seo_name": "Men's Wigs",
                            "is_displayCms": 1,
                            "id": 936613,
                            "pic_url": "",
                            "left_or_right": 1
                        },
                        {
                            "is_active": 1,
                            "is_displaySonCate": 1,
                            "cmsType": 1,
                            "cmsTypeId": "1710",
                            "display_style": 2,
                            "pid": 933778,
                            "display_name": "T-Shirts & Tanks",
                            "is_display_red": 0,
                            "is_wordOrPic": 1,
                            "url": "/Buy-T-Shirts-Tanks-c1710",
                            "category_level": 2,
                            "is_endColumn": 0,
                            "category_icon": "hot",
                            "seo_name": "T-Shirts & Tanks",
                            "is_displayCms": 1,
                            "id": 933808,
                            "pic_url": "homecms/2016/201604/20160427/_cms_1461734885.jpg",
                            "left_or_right": 1
                        },
                        {
                            "is_active": 1,
                            "is_displaySonCate": 1,
                            "cmsType": 1,
                            "cmsTypeId": "1495",
                            "display_style": 2,
                            "pid": 25278,
                            "display_name": "Jewelry",
                            "is_display_red": 0,
                            "is_wordOrPic": 1,
                            "url": "/Buy-Men-Jewelry-c1495",
                            "category_level": 2,
                            "is_endColumn": 0,
                            "category_icon": "new",
                            "seo_name": "Men Jewelry",
                            "is_displayCms": 1,
                            "id": 25320,
                            "pic_url": "",
                            "left_or_right": 1
                        },
                        {
                            "is_active": 1,
                            "is_displaySonCate": 1,
                            "cmsType": 1,
                            "cmsTypeId": "1157",
                            "display_style": 2,
                            "pid": 933778,
                            "display_name": "Polo Shirts",
                            "is_display_red": 0,
                            "is_wordOrPic": 1,
                            "url": "/Buy-Polo-Shirts-c1157",
                            "category_level": 2,
                            "is_endColumn": 0,
                            "category_icon": "",
                            "seo_name": "Polo Shirts",
                            "is_displayCms": 1,
                            "id": 933800,
                            "pic_url": "homecms/2016/201604/20160427/_cms_1461734858.jpg",
                            "left_or_right": 1
                        },
                        {
                            "is_active": 1,
                            "is_displaySonCate": 1,
                            "cmsType": 1,
                            "cmsTypeId": "1156",
                            "display_style": 2,
                            "pid": 933778,
                            "display_name": "Shirts",
                            "is_display_red": 0,
                            "is_wordOrPic": 1,
                            "url": "/Buy-Men-S-Shirts-c1156",
                            "category_level": 2,
                            "is_endColumn": 0,
                            "category_icon": "hot",
                            "seo_name": "Men's Shirts",
                            "is_displayCms": 1,
                            "id": 933802,
                            "pic_url": "homecms/2016/201604/20160427/_cms_1461734944.jpg",
                            "left_or_right": 1
                        },
                        {
                            "is_active": 1,
                            "is_displaySonCate": 1,
                            "cmsType": 1,
                            "cmsTypeId": "1169",
                            "display_style": 2,
                            "pid": 933778,
                            "display_name": "Blazers",
                            "is_display_red": 0,
                            "is_wordOrPic": 1,
                            "url": "/Buy-Blazers-Sportcoats-c1169",
                            "category_level": 2,
                            "is_endColumn": 0,
                            "category_icon": "",
                            "seo_name": "Blazers & Sportcoats",
                            "is_displayCms": 1,
                            "id": 933846,
                            "pic_url": "homecms/2016/201604/20160427/_cms_1461734909.jpg",
                            "left_or_right": 1
                        },
                        {
                            "is_active": 1,
                            "is_displaySonCate": 1,
                            "cmsType": 1,
                            "cmsTypeId": "1163",
                            "display_style": 2,
                            "pid": 933778,
                            "display_name": "Hoodies & Sweatshirts",
                            "is_display_red": 0,
                            "is_wordOrPic": 1,
                            "url": "/Buy-Men-S-Hoodies-Sweatshirts-c1163",
                            "category_level": 2,
                            "is_endColumn": 0,
                            "category_icon": "hot",
                            "seo_name": "Men's Hoodies & Sweatshirts",
                            "is_displayCms": 1,
                            "id": 933792,
                            "pic_url": "homecms/2016/201604/20160427/_cms_1461734845.jpg",
                            "left_or_right": 1
                        },
                        {
                            "is_active": 1,
                            "is_displaySonCate": 1,
                            "cmsType": 1,
                            "cmsTypeId": "1167",
                            "display_style": 2,
                            "pid": 933778,
                            "display_name": "Jeans",
                            "is_display_red": 0,
                            "is_wordOrPic": 1,
                            "url": "/Buy-Men-S-Jeans-c1167",
                            "category_level": 2,
                            "is_endColumn": 0,
                            "category_icon": "",
                            "seo_name": "Men's Jeans",
                            "is_displayCms": 1,
                            "id": 933832,
                            "pic_url": "homecms/2016/201604/20160427/_cms_1461734921.jpg",
                            "left_or_right": 1
                        },
                        {
                            "is_active": 1,
                            "is_displaySonCate": 1,
                            "cmsType": 1,
                            "cmsTypeId": "1714",
                            "display_style": 2,
                            "pid": 933778,
                            "display_name": "Leather & Faux Leather Jackets",
                            "is_display_red": 0,
                            "is_wordOrPic": 1,
                            "url": "/Buy-Men-S-Leather-Jackets-c1714",
                            "category_level": 2,
                            "is_endColumn": 0,
                            "category_icon": "",
                            "seo_name": "Men's Leather and Faux Leather Jackets",
                            "is_displayCms": 1,
                            "id": 936895,
                            "pic_url": "homecms/2016/201604/20160427/_cms_1461734895.jpg",
                            "left_or_right": 1
                        },
                        {
                            "is_active": 1,
                            "is_displaySonCate": 1,
                            "cmsType": 1,
                            "cmsTypeId": "1445",
                            "display_style": 2,
                            "pid": 933778,
                            "display_name": "Pants",
                            "is_display_red": 0,
                            "is_wordOrPic": 1,
                            "url": "/Buy-Men-S-Pants-c1445",
                            "category_level": 2,
                            "is_endColumn": 0,
                            "category_icon": "",
                            "seo_name": "Men's Pants",
                            "is_displayCms": 1,
                            "id": 933820,
                            "pic_url": "homecms/2016/201602/20160202/_cms_1454401645.jpg",
                            "left_or_right": 1
                        }],
                    "seo_name": "Men",
                    "is_displayCms": 1,
                    "id": 24578,
                    "position": 1744,
                    "left_or_right": 1
                },
                {
                    "is_active": 1,
                    "is_displaySonCate": 1,
                    "top_key": "wedding",
                    "cmsType": 1,
                    "cmsTypeId": "391",
                    "display_style": 2,
                    "pid": -1,
                    "display_name": "Wedding",
                    "is_display_red": 0,
                    "is_wordOrPic": 1,
                    "url": "/Buy-Wedding-c391",
                    "category_level": 0,
                    "is_endColumn": 0,
                    "children": [{
                        "is_active": 1,
                        "is_displaySonCate": 1,
                        "cmsType": 2,
                        "cmsTypeId": "Beach-Wedding-Dresses",
                        "display_style": 2,
                        "pid": 933346,
                        "display_name": "Beach",
                        "is_display_red": 0,
                        "is_wordOrPic": 1,
                        "url": "/gs/Beach-Wedding-Dresses",
                        "category_level": 2,
                        "is_endColumn": 0,
                        "category_icon": "",
                        "seo_name": "Beach Wedding Dresses",
                        "is_displayCms": 1,
                        "id": 933388,
                        "pic_url": "",
                        "left_or_right": 1
                    },
                        {
                            "is_active": 1,
                            "is_displaySonCate": 1,
                            "cmsType": 1,
                            "cmsTypeId": "392",
                            "display_style": 0,
                            "pid": 24814,
                            "display_name": "Wedding Dresses",
                            "is_display_red": 1,
                            "is_wordOrPic": 1,
                            "url": "/Buy-Wedding-Dresses-c392",
                            "category_level": 1,
                            "is_endColumn": 0,
                            "category_icon": "",
                            "seo_name": "Wedding Dresses",
                            "is_displayCms": 1,
                            "id": 933346,
                            "pic_url": "homecms/2016/201604/20160421/_cms_1461228851.jpg",
                            "left_or_right": 1
                        },
                        {
                            "is_active": 1,
                            "is_displaySonCate": 1,
                            "cmsType": 1,
                            "cmsTypeId": "829",
                            "display_style": 0,
                            "pid": 24814,
                            "display_name": "Wedding Party Dresses",
                            "is_display_red": 1,
                            "is_wordOrPic": 1,
                            "url": "/Buy-Wedding-Party-Dresses-c829",
                            "category_level": 1,
                            "is_endColumn": 0,
                            "category_icon": "",
                            "seo_name": "Wedding Party Dresses",
                            "is_displayCms": 1,
                            "id": 933352,
                            "pic_url": "",
                            "left_or_right": 1
                        },
                        {
                            "is_active": 1,
                            "is_displaySonCate": 1,
                            "cmsType": 1,
                            "cmsTypeId": "393",
                            "display_style": 2,
                            "pid": 933352,
                            "display_name": "Bridesmaid",
                            "is_display_red": 0,
                            "is_wordOrPic": 1,
                            "url": "/Buy-Bridesmaid-Dresses-c393",
                            "category_level": 2,
                            "is_endColumn": 0,
                            "category_icon": "hot",
                            "seo_name": "Bridesmaid Dresses",
                            "is_displayCms": 1,
                            "id": 933472,
                            "pic_url": "homecms/2016/201604/20160421/_cms_1461228860.jpg",
                            "left_or_right": 1
                        },
                        {
                            "is_active": 1,
                            "is_displaySonCate": 1,
                            "cmsType": 1,
                            "cmsTypeId": "633",
                            "display_style": 2,
                            "pid": 933352,
                            "display_name": "Mother of the Bride",
                            "is_display_red": 0,
                            "is_wordOrPic": 1,
                            "url": "/Buy-Mother-Of-The-Bride-Dresses-c633",
                            "category_level": 2,
                            "is_endColumn": 0,
                            "category_icon": "hot",
                            "seo_name": "Mother of the Bride Dresses",
                            "is_displayCms": 1,
                            "id": 933476,
                            "pic_url": "homecms/2016/201604/20160421/_cms_1461228879.jpg",
                            "left_or_right": 1
                        },
                        {
                            "is_active": 1,
                            "is_displaySonCate": 1,
                            "cmsType": 1,
                            "cmsTypeId": "562",
                            "display_style": 2,
                            "pid": 933352,
                            "display_name": "Flower Girl",
                            "is_display_red": 0,
                            "is_wordOrPic": 1,
                            "url": "/Buy-Flower-Girl-Dresses-c562",
                            "category_level": 2,
                            "is_endColumn": 0,
                            "category_icon": "",
                            "seo_name": "Flower Girl Dresses",
                            "is_displayCms": 1,
                            "id": 933474,
                            "pic_url": "homecms/2016/201604/20160421/_cms_1461228869.jpg",
                            "left_or_right": 1
                        },
                        {
                            "is_active": 1,
                            "is_displaySonCate": 1,
                            "cmsType": 6,
                            "cmsTypeId": "",
                            "display_style": 0,
                            "pid": 933604,
                            "display_name": "Milanoo Exclusive",
                            "is_display_red": 0,
                            "is_wordOrPic": 1,
                            "url": "/nf/gs/Milanoo-Exclusive-Designer-Collection",
                            "category_level": 2,
                            "is_endColumn": 0,
                            "category_icon": "",
                            "seo_name": "Milanoo Exclusive",
                            "is_displayCms": 1,
                            "id": 933606,
                            "pic_url": "homecms/2016/201604/20160421/_cms_1461229912.jpg",
                            "left_or_right": 2
                        },
                        {
                            "is_active": 0,
                            "is_displaySonCate": 1,
                            "cmsType": 1,
                            "cmsTypeId": "574",
                            "display_style": 2,
                            "pid": 934539,
                            "display_name": "Evening Dresses",
                            "is_display_red": 0,
                            "is_wordOrPic": 1,
                            "url": "/Buy-Evening-Dresses-c574",
                            "category_level": 2,
                            "is_endColumn": 0,
                            "category_icon": "hot",
                            "seo_name": "Evening Dresses",
                            "is_displayCms": 1,
                            "id": 934541,
                            "pic_url": "homecms/2016/201604/20160421/_cms_1461228906.jpg",
                            "left_or_right": 1
                        },
                        {
                            "is_active": 0,
                            "is_displaySonCate": 1,
                            "cmsType": 1,
                            "cmsTypeId": "565",
                            "display_style": 2,
                            "pid": 934539,
                            "display_name": "Cocktail Dresses",
                            "is_display_red": 0,
                            "is_wordOrPic": 1,
                            "url": "/Buy-Cocktail-Dresses-c565",
                            "category_level": 2,
                            "is_endColumn": 0,
                            "category_icon": "",
                            "seo_name": "Cocktail Dresses",
                            "is_displayCms": 1,
                            "id": 934545,
                            "pic_url": "homecms/2016/201604/20160421/_cms_1461228922.jpg",
                            "left_or_right": 1
                        },
                        {
                            "is_active": 0,
                            "is_displaySonCate": 1,
                            "cmsType": 1,
                            "cmsTypeId": "394",
                            "display_style": 2,
                            "pid": 934539,
                            "display_name": "Prom Dresses",
                            "is_display_red": 0,
                            "is_wordOrPic": 1,
                            "url": "/Buy-Prom-Dresses-c394",
                            "category_level": 2,
                            "is_endColumn": 0,
                            "category_icon": "hot",
                            "seo_name": "Prom Dresses",
                            "is_displayCms": 1,
                            "id": 934547,
                            "pic_url": "homecms/2016/201604/20160421/_cms_1461228936.jpg",
                            "left_or_right": 1
                        },
                        {
                            "is_active": 1,
                            "is_displaySonCate": 1,
                            "cmsType": 1,
                            "cmsTypeId": "782",
                            "display_style": 0,
                            "pid": 24814,
                            "display_name": "Wedding Accessories",
                            "is_display_red": 1,
                            "is_wordOrPic": 1,
                            "url": "/Buy-Wedding-Accessories-c782",
                            "category_level": 1,
                            "is_endColumn": 1,
                            "category_icon": "",
                            "seo_name": "Wedding Accessories",
                            "is_displayCms": 1,
                            "id": 933366,
                            "pic_url": "homecms/2016/201601/20160119/_cms_1453172187.jpg",
                            "left_or_right": 1
                        },
                        {
                            "is_active": 1,
                            "is_displaySonCate": 1,
                            "cmsType": 1,
                            "cmsTypeId": "2520",
                            "display_style": 0,
                            "pid": 24814,
                            "display_name": "Wedding Reception",
                            "is_display_red": 0,
                            "is_wordOrPic": 1,
                            "url": "/Buy-Wedding-Reception-c2520",
                            "category_level": 1,
                            "is_endColumn": 0,
                            "category_icon": "",
                            "seo_name": "Wedding Reception",
                            "is_displayCms": 1,
                            "id": 933364,
                            "pic_url": "homecms/2016/201601/20160119/_cms_1453172201.jpg",
                            "left_or_right": 1
                        }],
                    "seo_name": "Wedding",
                    "is_displayCms": 1,
                    "id": 24814,
                    "position": 1740,
                    "left_or_right": 1
                },
                {
                    "is_active": 1,
                    "is_displaySonCate": 1,
                    "top_key": "Shoes",
                    "cmsType": 1,
                    "cmsTypeId": "1399",
                    "display_style": 2,
                    "pid": -1,
                    "display_name": "Shoes",
                    "is_display_red": 0,
                    "is_wordOrPic": 1,
                    "url": "/Buy-Shoes-c1399",
                    "category_level": 0,
                    "is_endColumn": 0,
                    "children": [{
                        "is_active": 1,
                        "is_displaySonCate": 0,
                        "cmsType": 2,
                        "cmsTypeId": "Shoe-New-in",
                        "display_style": 0,
                        "pid": 24594,
                        "display_name": "New in",
                        "is_display_red": 0,
                        "is_wordOrPic": 1,
                        "url": "/gs/Shoe-New-in",
                        "category_level": 1,
                        "is_endColumn": 0,
                        "category_icon": "",
                        "seo_name": "",
                        "is_displayCms": 1,
                        "id": 935923,
                        "pic_url": "",
                        "left_or_right": 2
                    },
                        {
                            "is_active": 1,
                            "is_displaySonCate": 1,
                            "cmsType": 1,
                            "cmsTypeId": "618",
                            "display_style": 2,
                            "pid": 24596,
                            "display_name": "Sandals",
                            "is_display_red": 0,
                            "is_wordOrPic": 1,
                            "url": "/Buy-Sandals-c618",
                            "category_level": 2,
                            "is_endColumn": 0,
                            "category_icon": "hot",
                            "seo_name": "Sandals",
                            "is_displayCms": 1,
                            "id": 24606,
                            "pic_url": "homecms/2016/201604/20160427/_cms_1461738535.jpg",
                            "left_or_right": 1
                        },
                        {
                            "is_active": 0,
                            "is_displaySonCate": 1,
                            "cmsType": 1,
                            "cmsTypeId": "2370",
                            "display_style": 2,
                            "pid": 24598,
                            "display_name": "Pointy Toe Heels",
                            "is_display_red": 0,
                            "is_wordOrPic": 1,
                            "url": "/Buy-Pointy-Toe-Heels-c2370",
                            "category_level": 3,
                            "is_endColumn": 0,
                            "category_icon": "",
                            "seo_name": "Pointy Toe Heels",
                            "is_displayCms": 1,
                            "id": 24650,
                            "pic_url": "homecms/2016/201604/20160427/_cms_1461737638.jpg",
                            "left_or_right": 1
                        },
                        {
                            "is_active": 1,
                            "is_displaySonCate": 1,
                            "cmsType": 1,
                            "cmsTypeId": "627",
                            "display_style": 2,
                            "pid": 24598,
                            "display_name": "Peep Toe",
                            "is_display_red": 0,
                            "is_wordOrPic": 1,
                            "url": "/Buy-Peep-Toes-c627",
                            "category_level": 3,
                            "is_endColumn": 0,
                            "category_icon": "",
                            "seo_name": "Peep Toes",
                            "is_displayCms": 1,
                            "id": 24652,
                            "pic_url": "homecms/2016/201604/20160428/_cms_1461807379.jpg",
                            "left_or_right": 1
                        },
                        {
                            "is_active": 1,
                            "is_displaySonCate": 1,
                            "cmsType": 1,
                            "cmsTypeId": "9573",
                            "display_style": 2,
                            "pid": 933848,
                            "display_name": "Custom high heels",
                            "is_display_red": 0,
                            "is_wordOrPic": 1,
                            "url": "/Buy-Custom-High-Heels-c9573",
                            "category_level": 2,
                            "is_endColumn": 0,
                            "category_icon": "new",
                            "seo_name": "Custom high heels",
                            "is_displayCms": 1,
                            "id": 938357,
                            "pic_url": "",
                            "left_or_right": 1
                        },
                        {
                            "is_active": 1,
                            "is_displaySonCate": 1,
                            "cmsType": 1,
                            "cmsTypeId": "2360",
                            "display_style": 2,
                            "pid": 24598,
                            "display_name": "High Heels",
                            "is_display_red": 0,
                            "is_wordOrPic": 1,
                            "url": "/Buy-High-Heels-c2360",
                            "category_level": 3,
                            "is_endColumn": 0,
                            "category_icon": "",
                            "seo_name": "High Heels",
                            "is_displayCms": 1,
                            "id": 24654,
                            "pic_url": "homecms/2016/201604/20160427/_cms_1461737651.jpg",
                            "left_or_right": 1
                        },
                        {
                            "is_active": 1,
                            "is_displaySonCate": 1,
                            "cmsType": 1,
                            "cmsTypeId": "2372",
                            "display_style": 2,
                            "pid": 24598,
                            "display_name": "Platform Pumps",
                            "is_display_red": 0,
                            "is_wordOrPic": 1,
                            "url": "/Buy-Platform-Pumps-c2372",
                            "category_level": 3,
                            "is_endColumn": 0,
                            "category_icon": "",
                            "seo_name": "Platform Pumps",
                            "is_displayCms": 1,
                            "id": 24658,
                            "pic_url": "homecms/2016/201604/20160427/_cms_1461737679.jpg",
                            "left_or_right": 1
                        },
                        {
                            "is_active": 1,
                            "is_displaySonCate": 1,
                            "cmsType": 1,
                            "cmsTypeId": "1698",
                            "display_style": 2,
                            "pid": 933848,
                            "display_name": "Dance Shoes",
                            "is_display_red": 0,
                            "is_wordOrPic": 1,
                            "url": "/Buy-Dance-Shoes-c1698",
                            "category_level": 2,
                            "is_endColumn": 0,
                            "category_icon": "hot",
                            "seo_name": "Dance Shoes",
                            "is_displayCms": 1,
                            "id": 933850,
                            "pic_url": "homecms/2016/201604/20160427/_cms_1461737724.jpg",
                            "left_or_right": 1
                        },
                        {
                            "is_active": 1,
                            "is_displaySonCate": 1,
                            "cmsType": 1,
                            "cmsTypeId": "544",
                            "display_style": 2,
                            "pid": 933848,
                            "display_name": "Sexy Shoes",
                            "is_display_red": 0,
                            "is_wordOrPic": 1,
                            "url": "/Buy-Sexy-Shoes-c544",
                            "category_level": 2,
                            "is_endColumn": 0,
                            "category_icon": "",
                            "seo_name": "Sexy Shoes",
                            "is_displayCms": 1,
                            "id": 933854,
                            "pic_url": "homecms/2016/201604/20160427/_cms_1461737755.jpg",
                            "left_or_right": 1
                        },
                        {
                            "is_active": 1,
                            "is_displaySonCate": 1,
                            "cmsType": 1,
                            "cmsTypeId": "3282",
                            "display_style": 2,
                            "pid": 933848,
                            "display_name": "Evening shoes",
                            "is_display_red": 0,
                            "is_wordOrPic": 1,
                            "url": "/Buy-Evening-Shoes-c3282",
                            "category_level": 2,
                            "is_endColumn": 0,
                            "category_icon": "",
                            "seo_name": "Evening shoes",
                            "is_displayCms": 1,
                            "id": 933852,
                            "pic_url": "homecms/2016/201604/20160427/_cms_1461737736.jpg",
                            "left_or_right": 1
                        },
                        {
                            "is_active": 1,
                            "is_displaySonCate": 1,
                            "cmsType": 1,
                            "cmsTypeId": "2464",
                            "display_style": 2,
                            "pid": 24624,
                            "display_name": "Loafers",
                            "is_display_red": 0,
                            "is_wordOrPic": 1,
                            "url": "/Buy-Men-S-Loafers-c2464",
                            "category_level": 2,
                            "is_endColumn": 0,
                            "category_icon": "hot",
                            "seo_name": "Men's Loafers",
                            "is_displayCms": 1,
                            "id": 24626,
                            "pic_url": "homecms/2016/201604/20160427/_cms_1461737782.jpg",
                            "left_or_right": 1
                        },
                        {
                            "is_active": 1,
                            "is_displaySonCate": 1,
                            "cmsType": 1,
                            "cmsTypeId": "1357",
                            "display_style": 2,
                            "pid": 24624,
                            "display_name": "Sneakers",
                            "is_display_red": 0,
                            "is_wordOrPic": 1,
                            "url": "/Buy-Men-S-Sneakers-c1357",
                            "category_level": 2,
                            "is_endColumn": 0,
                            "category_icon": "new",
                            "seo_name": "Men's Sneakers",
                            "is_displayCms": 1,
                            "id": 24638,
                            "pic_url": "homecms/2016/201604/20160427/_cms_1461737789.jpg",
                            "left_or_right": 1
                        }],
                    "seo_name": "Shoes",
                    "is_displayCms": 1,
                    "id": 24594,
                    "position": 1746,
                    "left_or_right": 1
                },
                {
                    "is_active": 1,
                    "is_displaySonCate": 1,
                    "top_key": "hobbies",
                    "cmsType": 1,
                    "cmsTypeId": "8709",
                    "display_style": 2,
                    "pid": -1,
                    "display_name": "Costumes",
                    "is_display_red": 0,
                    "is_wordOrPic": 1,
                    "url": "/Buy-Costume-c8709",
                    "category_level": 0,
                    "is_endColumn": 0,
                    "children": [{
                        "is_active": 1,
                        "is_displaySonCate": 1,
                        "cmsType": 1,
                        "cmsTypeId": "314",
                        "display_style": 2,
                        "pid": 19480,
                        "display_name": "Catsuits & Zentai",
                        "is_display_red": 0,
                        "is_wordOrPic": 1,
                        "url": "/Buy-Catsuits-Zentai-c314",
                        "category_level": 2,
                        "is_endColumn": 0,
                        "category_icon": "hot",
                        "seo_name": "Catsuits & Zentai",
                        "is_displayCms": 1,
                        "id": 19496,
                        "pic_url": "homecms/2016/201605/20160506/_cms_1462519980.jpg",
                        "left_or_right": 1
                    },
                        {
                            "is_active": 0,
                            "is_displaySonCate": 1,
                            "cmsType": 1,
                            "cmsTypeId": "9119",
                            "display_style": 2,
                            "pid": 19480,
                            "display_name": "Sexy Lingerie",
                            "is_display_red": 0,
                            "is_wordOrPic": 1,
                            "url": "/Buy-Sexy-Lingerie-c9119",
                            "category_level": 2,
                            "is_endColumn": 0,
                            "category_icon": "",
                            "seo_name": "Sexy Lingerie",
                            "is_displayCms": 1,
                            "id": 934385,
                            "pic_url": "",
                            "left_or_right": 1
                        },
                        {
                            "is_active": 1,
                            "is_displaySonCate": 1,
                            "cmsType": 1,
                            "cmsTypeId": "396",
                            "display_style": 2,
                            "pid": 19480,
                            "display_name": "Sexy  Costumes",
                            "is_display_red": 0,
                            "is_wordOrPic": 1,
                            "url": "/Buy-Sexy-Costumes-c396",
                            "category_level": 2,
                            "is_endColumn": 0,
                            "category_icon": "hot",
                            "seo_name": "Sexy  Costumes",
                            "is_displayCms": 1,
                            "id": 19938,
                            "pic_url": "homecms/2016/201604/20160426/_cms_1461634441.jpg",
                            "left_or_right": 1
                        },
                        {
                            "is_active": 1,
                            "is_displaySonCate": 1,
                            "cmsType": 1,
                            "cmsTypeId": "2812",
                            "display_style": 2,
                            "pid": 19480,
                            "display_name": "Holidays Costumes",
                            "is_display_red": 0,
                            "is_wordOrPic": 1,
                            "url": "/Buy-Holidays-Costumes-c2812",
                            "category_level": 2,
                            "is_endColumn": 0,
                            "category_icon": "hot",
                            "seo_name": "Holidays Costumes",
                            "is_displayCms": 1,
                            "id": 935913,
                            "pic_url": "homecms/2016/201604/20160426/_cms_1461634488.jpg",
                            "left_or_right": 1
                        },
                        {
                            "is_active": 1,
                            "is_displaySonCate": 1,
                            "cmsType": 1,
                            "cmsTypeId": "1549",
                            "display_style": 2,
                            "pid": 19480,
                            "display_name": "Dance Costumes",
                            "is_display_red": 0,
                            "is_wordOrPic": 1,
                            "url": "/Buy-Dance-Costumes-c1549",
                            "category_level": 2,
                            "is_endColumn": 0,
                            "category_icon": "hot",
                            "seo_name": "Dance Costumes",
                            "is_displayCms": 1,
                            "id": 20320,
                            "pic_url": "homecms/2016/201604/20160426/_cms_1461634503.jpg",
                            "left_or_right": 1
                        },
                        {
                            "is_active": 1,
                            "is_displaySonCate": 1,
                            "cmsType": 1,
                            "cmsTypeId": "2186",
                            "display_style": 2,
                            "pid": 16398,
                            "display_name": "Anime Department",
                            "is_display_red": 1,
                            "is_wordOrPic": 1,
                            "url": "/Buy-Anime-Department-c2186",
                            "category_level": 2,
                            "is_endColumn": 0,
                            "category_icon": "hot",
                            "seo_name": "Anime Department",
                            "is_displayCms": 1,
                            "id": 16414,
                            "pic_url": "homecms/2016/201606/20160628/_cms_1467079981.jpg",
                            "left_or_right": 1
                        },
                        {
                            "is_active": 1,
                            "is_displaySonCate": 1,
                            "cmsType": 1,
                            "cmsTypeId": "1543",
                            "display_style": 2,
                            "pid": 16398,
                            "display_name": "Anime Merchandise",
                            "is_display_red": 0,
                            "is_wordOrPic": 1,
                            "url": "/Buy-Anime-Merchandise-c1543",
                            "category_level": 2,
                            "is_endColumn": 0,
                            "category_icon": "",
                            "seo_name": "Anime Merchandise",
                            "is_displayCms": 1,
                            "id": 19038,
                            "pic_url": "homecms/2016/201606/20160628/_cms_1467080184.jpg",
                            "left_or_right": 1
                        },
                        {
                            "is_active": 1,
                            "is_displaySonCate": 1,
                            "cmsType": 1,
                            "cmsTypeId": "301",
                            "display_style": 2,
                            "pid": 16398,
                            "display_name": "Cosplay Wigs",
                            "is_display_red": 1,
                            "is_wordOrPic": 1,
                            "url": "/Buy-Cosplay-Wigs-c301",
                            "category_level": 2,
                            "is_endColumn": 0,
                            "category_icon": "hot",
                            "seo_name": "Cosplay Wigs",
                            "is_displayCms": 1,
                            "id": 18574,
                            "pic_url": "homecms/2016/201606/20160628/_cms_1467080708.jpg",
                            "left_or_right": 1
                        },
                        {
                            "is_active": 1,
                            "is_displaySonCate": 1,
                            "cmsType": 1,
                            "cmsTypeId": "635",
                            "display_style": 2,
                            "pid": 20688,
                            "display_name": "Lolita Dresses",
                            "is_display_red": 0,
                            "is_wordOrPic": 1,
                            "url": "/Buy-Lolita-Dresses-c635",
                            "category_level": 2,
                            "is_endColumn": 0,
                            "category_icon": "hot",
                            "seo_name": "Lolita Dresses",
                            "is_displayCms": 1,
                            "id": 20704,
                            "pic_url": "homecms/2016/201604/20160426/_cms_1461634384.jpg",
                            "left_or_right": 1
                        },
                        {
                            "is_active": 1,
                            "is_displaySonCate": 1,
                            "cmsType": 1,
                            "cmsTypeId": "1006",
                            "display_style": 2,
                            "pid": 20688,
                            "display_name": "Lolita Outfits",
                            "is_display_red": 0,
                            "is_wordOrPic": 1,
                            "url": "/Buy-Lolita-Outfits-c1006",
                            "category_level": 2,
                            "is_endColumn": 0,
                            "category_icon": "",
                            "seo_name": "Lolita Outfits",
                            "is_displayCms": 1,
                            "id": 20974,
                            "pic_url": "homecms/2016/201604/20160426/_cms_1461634602.jpg",
                            "left_or_right": 1
                        },
                        {
                            "is_active": 1,
                            "is_displaySonCate": 1,
                            "cmsType": 1,
                            "cmsTypeId": "775",
                            "display_style": 2,
                            "pid": 20688,
                            "display_name": "Lolita Footwear",
                            "is_display_red": 0,
                            "is_wordOrPic": 1,
                            "url": "/Buy-Lolita-Footwear-c775",
                            "category_level": 2,
                            "is_endColumn": 0,
                            "category_icon": "hot",
                            "seo_name": "Lolita Footwear",
                            "is_displayCms": 1,
                            "id": 20910,
                            "pic_url": "homecms/2016/201604/20160426/_cms_1461634406.jpg",
                            "left_or_right": 1
                        }],
                    "seo_name": "Costumes",
                    "is_displayCms": 1,
                    "id": 16382,
                    "position": 1742,
                    "left_or_right": 1
                }]
        };
        tester.get(__path(__filename) + 'websiteId=1&languageCode=en-uk&deviceType=1')
            .expect(200)
            .end(function (err, res) {
                res.should.be.json;
                res.body.should.eql(expected);
                done();
            });
    });
});